host = "0.0.0.0"
port = 8001
dev_autoreload = false
model_listing_mode = "as_is"
api_key_check = "lm_proxy.api_key_check.allow_all.AllowAll"

[connections]
[connections.deepseek]
class = "src.llm_connection.OpenAIConnection"
api_base = "https://api.deepseek.com/"
api_key = "sk-ed1bfdd4acd94dd6b3b122be5dedf9d2"
model = "deepseek-v4-flash"

[connections.moonshot]
class = "src.llm_connection.OpenAIConnection"
api_base = "https://api.moonshot.ai/v1/"
api_key = ""
model = "kimi-k2.7-code"

[connections.minimax]
class = "src.llm_connection.OpenAIConnection"
api_base = "https://api.minimax.io/v1"
api_key = ""
model = "MiniMax-M3"

[connections.local]
class = "src.llm_connection.OpenAIConnection"
api_base = "http://localhost:10002/v1"
api_key = "123"
model = "qwen3.6"

[connections.xiaomi]
class = "src.llm_connection.OpenAIConnection"
api_base = "https://token-plan-sgp.xiaomimimo.com/v1"
api_key = ""
model = "mimo-v2.5-pro"

[connections."moonshot coding plan"]
class = "src.llm_connection.OpenAIConnection"
api_base = "https://api.kimi.com/coding/v1"
api_key = ""
model = "kimi-for-coding"

[[before]]
class = "src.server.ConnectionDefaultsHandler"

[before.defaults.deepseek]
reasoning_effort = "max"
thinking = true

[before.defaults.local]
reasoning_effort = "medium"

[before.defaults.xiaomi]
reasoning_effort = "high"
thinking = true

[routing]
"deepseek-v4-pro" = "deepseek.deepseek-v4-pro"
"deepseek-v4-flash" = "deepseek.deepseek-v4-flash"
"kimi-k2-0905-preview" = "moonshot.kimi-k2-0905-preview"
"MiniMax-M3" = "minimax.MiniMax-M3"
"MiniMax-M2.7" = "minimax.MiniMax-M2.7"
"local" = "local.qwen3.6"
"mimo-v2.5-pro" = "xiaomi.mimo-v2.5-pro"
"MiniMax-M2.7-highspeed" = "minimax.MiniMax-M2.7-highspeed"
"kimi-k2.7" = "moonshot coding plan.kimi-for-coding"
"kimi-k2.7-highspeed" = "moonshot coding plan.kimi-for-coding-highspeed"
"kimi-k3" = "moonshot coding plan.k3"

[groups]
[groups.default]
api_keys = ["YOUR_API_KEY_HERE"]
allowed_connections = "*"
